
package vistas;

import bd.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MIGUEL A. RODRIGUEZ
 */
public class ReporteTodasRutinas extends javax.swing.JFrame {

   UIManager UI;
    private Conexion conexion = new Conexion();

    public static BuscarAtletas addCedula;
    public ReporteTodasRutinas() {
        initComponents();
         setIconImage(getIconImage());
          SetImageLabel(LabelLogo, "src/img/logoJR3.png");
        this.setDefaultCloseOperation (JFrame.DO_NOTHING_ON_CLOSE);
        this.setTitle ("RUTINAS");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRutina1 = new javax.swing.JPanel();
        btnBuscarTodas_rutinas = new javax.swing.JButton();
        LabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(280, 205));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelRutina1.setBackground(new java.awt.Color(0, 0, 102));
        PanelRutina1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RUTINAS GENERAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell Extra Bold", 1, 14), new java.awt.Color(0, 102, 204))); // NOI18N
        PanelRutina1.setMinimumSize(new java.awt.Dimension(280, 205));
        PanelRutina1.setPreferredSize(new java.awt.Dimension(280, 205));
        PanelRutina1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarTodas_rutinas.setBackground(new java.awt.Color(0, 153, 204));
        btnBuscarTodas_rutinas.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        btnBuscarTodas_rutinas.setForeground(new java.awt.Color(0, 0, 153));
        btnBuscarTodas_rutinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonBuscar.png"))); // NOI18N
        btnBuscarTodas_rutinas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnBuscarTodas_rutinas.setContentAreaFilled(false);
        btnBuscarTodas_rutinas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonBuscar2.png"))); // NOI18N
        btnBuscarTodas_rutinas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonBuscar.png"))); // NOI18N
        btnBuscarTodas_rutinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTodas_rutinasActionPerformed(evt);
            }
        });
        PanelRutina1.add(btnBuscarTodas_rutinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 140, 30));

        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoJR3.png"))); // NOI18N
        PanelRutina1.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 150, 150));

        getContentPane().add(PanelRutina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 205));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarTodas_rutinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTodas_rutinasActionPerformed
        reportTodasRutinas();
        
        Operaciones_rutinas.todasRutinas = null;
         this.dispose();

    }//GEN-LAST:event_btnBuscarTodas_rutinasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteTodasRutinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteTodasRutinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteTodasRutinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteTodasRutinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReporteTodasRutinas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JPanel PanelRutina1;
    private javax.swing.JButton btnBuscarTodas_rutinas;
    // End of variables declaration//GEN-END:variables


/*  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  */
    
    public void reportTodasRutinas(){
        
        try {
            Connection conn = conexion.conectar();
            JasperReport reporte = null;
            //String path = "src/reportes/reportVerRutinas_todas.jasper";
            Map parametro = new HashMap();

            parametro.put("ruta_imagen", ReporteTodasRutinas.class.getResource("/reportes/logo1.png"));
            reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/reportes/reportVerRutinas_todas.jasper"));
           

            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, conn);

            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            view.setVisible(true);
            view.setTitle("RUTINAS");
        } catch (JRException e) {
        }
        
    }
    
     /* ************************************************************************************************************************************************************************** */
    private void SetImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    
     /*  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  */
     
     // FUNCION  PARA  MOSTRAR  LAS  IMAGENES  EN  EL  TITULO  DE  LAS  VENTANAS
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/logoVentana.png"));
        return retValue;
    }

    /* FUNCION  PARA  COLOCAR  ICONO  A LAS  VENTANAS DE DIALOGOS  DE LOS JOPCIONPANEL*/
    public Icon icono(String path, int width, int heigth) {
        Icon img = new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage().getScaledInstance(width, heigth, java.awt.Image.SCALE_SMOOTH));
        return img;
    }
    
    
    /*  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  */
    
    


}
